CREATE TABLE AGENT (
    ID BIGINT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    AGENTNAME VARCHAR(50) NOT NULL,
    AGENTCOVER VARCHAR(50) NOT NULL,
    FAVWEAPON VARCHAR(50) NOT NULL
 );

CREATE TABLE MISSION (
  ID BIGINT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  LOCATION VARCHAR(50) NOT NULL,
  CODENAME VARCHAR(50) NOT NULL
);