INSERT INTO MISSION (LOCATION, CODENAME) VALUES ('Honolulu', 'Dovolenka');
INSERT INTO MISSION (LOCATION, CODENAME) VALUES ('Kraliky', 'Pokosit');

INSERT INTO AGENT (AGENTNAME, AGENTCOVER, FAVWEAPON) VALUES ('Jozko', 'D.B.', 'pelendrek');