INSERT INTO MISSION (LOCATION, CODENAME) VALUES ('Jerusalem', 'Vianoce');
INSERT INTO MISSION (LOCATION, CODENAME) VALUES ('Kraliky', 'Pokosit');

INSERT INTO AGENT (AGENTNAME, AGENTCOVER, FAVWEAPON) VALUES ('Helena', 'Deadly Death', 'katana');
